In [1]:
#Ali Amir Khawaja 
#Intermediate-2-Prediction using Decision Tree Classifier
import pandas as pd
import numpy as np
import graphviz
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split


# Specify the path to your Excel file
excel_file = ''

# Read the excel file as a pandas DataFrame for different sheets and store them in a list
# Read the Excel file into a pandas DataFrame
data = pd.read_csv('/content/LGMVIP_DS_Internship-Task2-IntermediateLevel.csv')

# Now you can work with the data in the DataFrame
# For example, you can print the first few rows
#print(data)

data=np.array(data)
data=np.transpose(data)
x=np.transpose(data[1:5])
y=np.transpose(data[5:6])
print("Features:\n",x)
print()
print("Expected Output:\n",y)

Features:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 

In [2]:
# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [3]:
# Create a decision tree classifier
clf = DecisionTreeClassifier()

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy*100,"%")

Accuracy: 100.0 %


In [4]:
# Visualize the decision tree
dot_data = export_graphviz(clf, out_file=None, feature_names=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'], class_names=['Iris-setosa','Iris-virginica','Iris-versicolor'], filled=True, rounded=True, special_characters=True)
graph = graphviz.Source(dot_data)
graph.render("decision_tree")
graph.view()

'decision_tree.pdf'

In [5]:
#150	5.9	3	5.1	1.8	Iris-virginica
id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm=0,0,0,0,0
SepalLengthCm=input("Enter Sepal(LengthCm):")
SepalWidthCm=input("Enter Sepal(WidthCm):")
PetalLengthCm=input("Enter Petal(LengthCm):")
PetalWidthCm=input("Enter Petal(WidthCm):")
arr=[SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm]
features=np.reshape(arr,(1,4))
prediction=clf.predict(features)
print("")
print("According to the Entered Featutres:")
print("SepalLengthCm:",SepalLengthCm)
print("SepalWidthCm:",SepalWidthCm)
print("PetalLengthCm:",PetalLengthCm)
print("PetalWidthCm:",PetalWidthCm)
print()
print("The Predicted Flower is",prediction[0])

Enter Sepal(LengthCm):5.9
Enter Sepal(WidthCm):3
Enter Petal(LengthCm):5.1
Enter Petal(WidthCm):1.8

According to the Entered Featutres:
SepalLengthCm: 5.9
SepalWidthCm: 3
PetalLengthCm: 5.1
PetalWidthCm: 1.8

The Predicted Flower is Iris-virginica
